ALTER TABLE TBL_MTR_COMPANY ADD COLUMN IF NOT EXISTS nit TEXT default NULL; 

ALTER TABLE TBL_MTR_COMPANY ADD COLUMN IF NOT EXISTS phone TEXT default NULL; 

ALTER TABLE TBL_MTR_COMPANY ADD COLUMN IF NOT EXISTS boxedAddress LONGTEXT default NULL; 

ALTER TABLE TBL_MTR_COMPANY ADD COLUMN IF NOT EXISTS cityNameSender TEXT default NULL; 

ALTER TABLE TBL_MTR_COMPANY ADD COLUMN IF NOT EXISTS stateNameSender TEXT default NULL; 
